### ISSUE TITLE
Convert model, KeyError: 'assets'; IndexError: list index out of range

### ISSUE THREAD

**Issue by Samuel-wei** [BumbleBee-BBStream/yolov7#19]
# Convert model
# Error:
root@0a9e8aae3707:/home/workspace/yolov7# python3 export_yoloV7.py -w /home/workspace/BatteryDetect/models/small_defect_JinChuan_V6.3/weights/best.pt -s 640 640 --dynamic
```

Starting: /home/workspace/BatteryDetect/models/small_defect_JinChuan_V6.3/weights/best.pt
Opening YOLOv7 model

Traceback (most recent call last):
  File "/home/workspace/yolov7/utils/google_utils.py", line 26, in attempt_download
    assets = [x['name'] for x in response['assets']]  # release assets
KeyError: 'assets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_yoloV7.py", line 124, in <module>
    sys.exit(main(args))
  File "export_yoloV7.py", line 56, in main
    model = yolov7_export(args.weights, device)
  File "export_yoloV7.py", line 34, in yolov7_export
    model = attempt_load(weights, map_location=device)
  File "/home/workspace/yolov7/models/experimental.py", line 251, in attempt_load
    attempt_download(w)
  File "/home/workspace/yolov7/utils/google_utils.py", line 31, in attempt_download
    tag = subprocess.check_output('git tag', shell=True).decode().split()[-1]
IndexError: list index out of range
```

_Originally posted by @Samuel-wei in https://github.com/BumbleBee-BBStream/BBStream/issues/127#issuecomment-1663052743_

**Comment by Samuel-wei** [comment]
# Solving
[yolov7/utils/google_utils.py](https://github.com/WongKinYiu/yolov7/blob/8c0bf3f78947a2e81a1d552903b4934777acfa5f/utils/google_utils.py#L25)
Line 25 in [8c0bf3f](https://github.com/WongKinYiu/yolov7/commit/8c0bf3f78947a2e81a1d552903b4934777acfa5f)

 `response = requests.get(f'https://api.github.com/repos/{repo}/releases/latest').json()  # github api `
modify like this :

`response = requests.get(f'https://api.github.com/repos/{repo}/releases/71389134').json() `
or

```
response = requests.get(f'https://api.github.com/repos/WongKinYiu/yolov7/releases/latest').json()
if response['message'] == 'Not Found':
    response = requests.get(f'https://api.github.com/repos/WongKinYiu/yolov7/releases').json()
    response = requests.get(response[0]["url"]).json()
```
